config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root to: 'leagues#index'

	resources :games do 
		get :fixture, on: :collection
		get :table, on: :collection
	end

	resources :teams
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :local_team, class_name: "Team", foreign_key: "local_team_id"
  belongs_to :visitor_team, class_name: "Team", foreign_key: "visitor_team_id"

  POINTS = {win: {local_points: 3, visitor_points: 0}, loose: {local_points: 0, visitor_points: 3}, draw: {local_points: 1, visitor_points: 1}}

  validates :local_goals, :visitor_goals, numericality: { greater_than_or_equal_to: 0 }, unless: :new_record?

  def assign_points
    update POINTS[:win] if local_goals > visitor_goals
    update POINTS[:loose] if local_goals < visitor_goals
    update POINTS[:draw] if local_goals == visitor_goals
  end

  def self.schedule
    teams = Team.all.to_a
    (0...teams.size-1).map do |r|
      t = teams.dup
      first_team = t.shift
      r.times { |i| t << t.shift }
      t = t.unshift(first_team)
      tms_away = t[0...teams.size/2]
      tms_home = t[teams.size/2...teams.size].reverse

      (0...(teams.size/2)).map do |i|
        create! local_team:tms_home[i], visitor_team: tms_away[i], fixture: r + 1
        [tms_away[i],tms_home[i]]
      end
    end
  end

end

app/models/team.rb
class Team < ApplicationRecord
  has_many :games_as_local, class_name: "Game", foreign_key: "local_team_id"
  has_many :games_as_visitor, class_name: "Game", foreign_key: "visitor_team_id"

  def calculate_points
    local = games_as_local
    visitor = games_as_visitor

    points = local.sum(:local_points) + visitor.sum(:visitor_points)
    goals_for = local.sum(:local_goals) + visitor.sum(:visitor_goals)
    goals_against = local.sum(:visitor_goals) + visitor.sum(:local_goals)
    games_played = local.where.not(local_goals: nil).count + visitor.where.not(visitor_goals: nil).count
    games_won = local.where("local_goals > visitor_goals").count + visitor.where("local_goals < visitor_goals").count
    games_lost = local.where("local_goals < visitor_goals").count + visitor.where("local_goals > visitor_goals").count
    games_draw = local.where("local_goals = visitor_goals").count + visitor.where("local_goals = visitor_goals").count

    update points: points, goals_for: goals_for, goals_against: goals_against, games_played: games_played, games_won: games_won, games_lost: games_lost, games_draw: games_draw
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @fixtures = Game.order(fixture: :asc).group_by(&:fixture)
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        @game.assign_points
        @game.visitor_team.calculate_points
        @game.local_team.calculate_points

        format.html { redirect_to games_path, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def table
    @teams = Team.order(points: :desc, goals_for: :desc, goals_against: :asc)
  end

  def fixture
    Game.destroy_all
    Game.schedule
    Team.all.map(&:calculate_points)

    redirect_to games_path, notice: "Your League is ready to start!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:local_goals, :visitor_goals)
    end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

	def index
		render 'index'
	end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
	
	def index
		@teams = Team.all
		render 'index'
	end

	def view_table
		@teams = Team.order(points: :desc)
		render 'table'
	end

	def new
		@team = Team.new
		render 'new'
	end

	def create
		@team = Team.new(team_params)
		@team.save
		redirect_to '/teams'
	end

	private

	def team_params
		params.require(:team).permit(:name, :stadium)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/_form.html.erb
<%= form_for(game) do |f| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :local_goals, "Goals for #{game.local_team.name} (local)" %>
    <%= f.text_field :local_goals %>
  </div>

  <div class="field">
    <%= f.label :visitor_goals, "Goals for #{game.visitor_team.name} (visitor)" %>
    <%= f.text_field :visitor_goals %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Games</h1>
<button class="btn btn-default">
  <%= link_to 'Back', root_path, method: :get %>
</button>
<button class="btn btn-default">
  <%= link_to 'View table', table_games_path %>
</button>

<% @game_fixture = "" %>
<table class="table table-striped ">
  <% @fixtures.each do |fixture, games| %>

      <thead>
      <td colspan="4"><h2>Fixture <%= fixture %></h2></td>
      </thead>

      <thead>
      <th>Teams</th>
      <th>Result</th>
      <th>Date</th>
      <th>Options</th>
      </thead>


      <tbody>
      <% games.each do |game| %>
          <tr>
            <td><%= game.local_team.name %> vs <%= game.visitor_team.name %></td>
            <td><%= game.local_goals %> - <%= game.visitor_goals %></td>
            <td><%= game.game_date_time %></td>
            <td>
              <%= link_to('Edit', edit_game_path(game), method: :get) %>
            </td>

          </tr>
      <% end %>
      </tbody>
  <% end %>
</table>


<button>
  <%= link_to 'Back', root_path, method: :get %>
</button>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Local goals:</strong>
  <%= @game.local_goals %>
</p>

<p>
  <strong>Visitor goals:</strong>
  <%= @game.visitor_goals %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/games/table.html.erb
<h1>Table</h1>

<table class="table table-striped table-responsive">
	<thead>
		<th>Position</th>
		<th>Name</th>
		<th>Played</th>
		<th>Won</th>
		<th>Lost</th>
		<th>Draw</th>
		<th>GF</th>
		<th>GA</th>
		<th>GD</th>
		<th>Points</th>
	</thead>
	<% @teams.each.with_index do |team, index| %>
		<tr>
			<td><%= index + 1 %></td>
			<td><%= team.name %></td>
			<td><%= team.games_played %></td>
			<td><%= team.games_won %></td>
			<td><%= team.games_lost %></td>
			<td><%= team.games_draw %></td>
			<td><%= team.goals_for %></td>
			<td><%= team.goals_against %></td>
			<td><%= team.goals_for - team.goals_against %></td>
			<td><%= team.points %></td>
		</tr>
	<% end %>

</table>

<button class="btn btn-default">
		<%= link_to 'Back', root_path, method: :get %>	
</button>

<button class="btn btn-default">
		<%= link_to 'View fixtures', games_path %>	
</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amaleague</title>
    <%= csrf_meta_tags %>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" type="text/css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" type="text/css" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <div class="container">
      <div class="container">
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>


        <%= yield %>


        <%= debug(params) if Rails.env.development? %>
      </div>
	  </div>
    
  </body>
</html>

app/views/leagues/index.html.erb
<html>
<head>
	<meta charset="UTF-8">
	<title>League</title>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-sm-12 text-center">
				<h1>Welcome to Ventorro del Cano League</h1>		
			</div>
		</div>
		<div class="row">
			<div class="col-md-4 text-center">
				<div class="thumbnail">
					<i class="fa fa-users" aria-hidden="true"></i>
					<button class="btn btn-default">
						<%= link_to 'View teams', teams_path %>	
					</button>
				</div>
			</div>
			<div class="col-md-4 text-center">
				<div class="thumbnail">
					<i class="fa fa-table" aria-hidden="true"></i>
					<button class="btn btn-default">
						<%= link_to 'View fixtures', games_path %>	
					</button>
				</div>
			</div>
			<div class="col-md-4 text-center">
				<div class="thumbnail">
					<i class="fa fa-line-chart" aria-hidden="true"></i>
					<button class="btn btn-default">
						<%= link_to 'View table', table_games_path %>
					</button>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 text-center">
				<button class="btn btn-default">
					<%= link_to 'Generate fixture', fixture_games_path %>

				</button>
			</div>
		</div>
	</div>
	

	
</body>
</html>